image: oarteam/batsim

build:clang:
  stage: build
  script:
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++
    - mkdir /builds/batsim/batsched/build
    - cd /builds/batsim/batsched/build
    - cmake .. -Dtreat_warnings_as_errors=ON
    - make
  artifacts:
    paths:
      - /builds/batsim/batsched/

# test:
#   stage: test
#   script:
#     # Let's run the redis server
#     - |
#       redis-server>/dev/null &
#       while ! nc -z localhost 6379; do
#         sleep 1
#       done

#     - cd /builds/batsim/batsched/build
#     - make install

#     - cd /builds/batsim/batsched
#     - /root/batsim/tools/experiments/execute_instances.py test/fast_tests.yaml
#   dependencies:
#     - build:clang
