image: oarteam/batsim_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - big_stage

###############################################################################
# Build and test
###############################################################################
build_and_test:
  stage: big_stage
  script:
    #-------------#
    # C++ library #
    #-------------#
    - nix flake show
    - nix build -L .#batprotocol-cpp
    - nix build -L .#ci-batprotocol-cpp-werror-gcc
    - nix build -L .#ci-batprotocol-cpp-werror-clang
    # tests
    - nix build -L .#ci-cpp-test
    - nix build -L -o result-cov-report .#ci-cpp-coverage-report
    - cat ./result-cov-report/file-summary.txt
    - cp -rL result-cov-report cpp-cov-report
    #----------------#
    # Python library #
    #----------------#
    # - nix-build -A batprotocol-py
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cpp-cov-report/cobertura.xml
