image: oarteam/batsim_ci

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - update_dependencies_cache
  - test
  - coverage

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    - ./ci/build.bash
    - find /builds/batsim/batsched/build
  artifacts:
    paths:
      - /builds/batsim/batsched/build

###############################################################################
# Dependencies cache stage
###############################################################################
update_dependencies_cache:
  stage: update_dependencies_cache
  script:
    - ./ci/update-dependencies-cache.bash

###############################################################################
# Test stage
###############################################################################
test_pinned_batsim:
  stage: test
  script:
    - find /builds/batsim/batsched/build
    - nix-shell ./ci -A test_deps_pinned --command './ci/run-tests.bash'
    - find /builds/batsim/batsched/build
  dependencies:
    - build
  artifacts:
    paths:
      - /builds/batsim/batsched/build

test_dev_batsim:
  stage: test
  script:
    - nix-shell ./ci -A test_deps_dev --command './ci/run-tests.bash'
  dependencies:
    - build

###############################################################################
# Coverage stage
###############################################################################
coverage:
  stage: coverage
  script:
    - find /builds/batsim/batsched/build
    - nix-shell ./ci -A test_deps_pinned --command './ci/analyze-coverage.bash'
  dependencies:
    - test_pinned_batsim
  artifacts:
    paths:
      - /builds/batsim/batsched/cover
