image: oarteam/batsim_ci

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - update_dependencies_cache

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    - ./ci/build.bash
  artifacts:
    paths:
      - /builds/batsim/batsched/build

###############################################################################
# Dependencies cache stage
###############################################################################
update_dependencies_cache:
  stage: update_dependencies_cache
  script:
    - ./ci/update-dependencies-cache.bash
