image: oarteam/batsim_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - big_stage

###############################################################################
# Build and test
###############################################################################
build_and_test:
  stage: big_stage
  script:
    #-------------#
    # C++ library #
    #-------------#
    - nix-shell --pure -A batprotocol-cpp --command '.ci/list-store-paths-for-cachix.bash' | cachix push batsim
    - nix-build -A batprotocol-cpp
    # tests
    - nix-shell --pure -A cpp-test --command '.ci/list-store-paths-for-cachix.bash' | grep -v 'batprotocol-cpp' | cachix push batsim
    - nix-build -A cpp-test
    - ./result/bin/batprotocol-cpp-test
    #----------------#
    # Python library #
    #----------------#
    - nix-build -A batprotocol-py
