image: oarteam/batsim_ci

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - update_dependencies_cache
  - test

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    - ./ci/build.bash

###############################################################################
# Dependencies cache stage
###############################################################################
update_dependencies_cache:
  stage: update_dependencies_cache
  script:
    - ./ci/update-dependencies-cache.bash

###############################################################################
# Test stage
###############################################################################
test_pinned_batsim:
  stage: test
  script:
    - nix-shell ./ci -A test_pinned --command './ci/run-tests.bash'

test_dev_batsim:
  stage: test
  script:
    - nix-shell ./ci -A test_dev --command './ci/run-tests.bash'
