[package]
name = "batprotocol-rust"
version = "0.1.0"
authors = ["Millian Poquet <millian.poquet@inria.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.8.2"

[lib]
